CREATE TABLE "status_shares" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sender_user_id" BIGINT NOT NULL,
    "recipient_user_id" BIGINT,
    "recipient_username_snapshot" VARCHAR(50),
    "token_hash" CHAR(64) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "expires_at" TIMESTAMP NOT NULL,
    "viewed_at" TIMESTAMP,
    "revoked_at" TIMESTAMP,
    "max_views" INTEGER NOT NULL DEFAULT 1,
    "view_count" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "status_shares_sender_user_id_fkey" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    CONSTRAINT "status_shares_recipient_user_id_fkey" FOREIGN KEY ("recipient_user_id") REFERENCES "users"("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "status_shares_token_hash_key" ON "status_shares"("token_hash");
CREATE INDEX "status_shares_sender_user_id_created_at_idx" ON "status_shares"("sender_user_id", "created_at");
CREATE INDEX "status_shares_recipient_user_id_created_at_idx" ON "status_shares"("recipient_user_id", "created_at");
