CREATE TYPE "ShipmentStatus" AS ENUM ('packed', 'shipped', 'delivered');

CREATE TABLE "shipments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL,
    "carrier" VARCHAR,
    "tracking_number" VARCHAR,
    "status" "ShipmentStatus" NOT NULL DEFAULT 'packed',
    "shipped_at" TIMESTAMP,
    "delivered_at" TIMESTAMP,
    CONSTRAINT "shipments_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE
);

CREATE INDEX "shipments_order_id_idx" ON "shipments"("order_id");
