CREATE TYPE "PaymentStatus" AS ENUM ('initiated', 'paid', 'failed', 'refunded');

CREATE TABLE "payments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT,
    "appointment_id" BIGINT,
    "payhere_reference" VARCHAR NOT NULL,
    "amount_cents" INTEGER NOT NULL,
    "status" "PaymentStatus" NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "payments_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL,
    CONSTRAINT "payments_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "payments_payhere_reference_key" ON "payments"("payhere_reference");
CREATE INDEX "payments_order_id_idx" ON "payments"("order_id");
CREATE INDEX "payments_appointment_id_idx" ON "payments"("appointment_id");
