CREATE TABLE "practitioners" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "name" VARCHAR NOT NULL,
    "specialization" VARCHAR NOT NULL,
    "reg_no" VARCHAR,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "practitioners_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "practitioners_user_id_key" ON "practitioners"("user_id");
CREATE INDEX "practitioners_specialization_idx" ON "practitioners"("specialization");
