CREATE TABLE "test_types" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "category" VARCHAR,
    "active" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX "test_types_name_key" ON "test_types"("name");
CREATE INDEX "test_types_category_idx" ON "test_types"("category");
