CREATE TYPE "ClinicStaffRole" AS ENUM ('clinic_admin', 'staff');

CREATE TABLE "clinic_staff" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clinic_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "role" "ClinicStaffRole" NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "clinic_staff_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE CASCADE,
    CONSTRAINT "clinic_staff_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "clinic_staff_clinic_id_user_id_key" ON "clinic_staff"("clinic_id", "user_id");
CREATE INDEX "clinic_staff_user_id_idx" ON "clinic_staff"("user_id");
