CREATE TABLE "clinics" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "address" TEXT NOT NULL,
    "lat" DECIMAL,
    "lng" DECIMAL,
    "available_time" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "clinics_name_idx" ON "clinics"("name");
