CREATE TYPE "AppointmentSlotMode" AS ENUM ('online', 'physical');

CREATE TABLE "appointment_slots" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "practitioner_id" BIGINT NOT NULL,
    "clinic_id" BIGINT,
    "mode" "AppointmentSlotMode" NOT NULL,
    "starts_at" TIMESTAMP NOT NULL,
    "ends_at" TIMESTAMP NOT NULL,
    "price_cents" INTEGER NOT NULL,
    "is_available" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "appointment_slots_practitioner_id_fkey" FOREIGN KEY ("practitioner_id") REFERENCES "practitioners"("id") ON DELETE CASCADE,
    CONSTRAINT "appointment_slots_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE SET NULL
);

CREATE INDEX "appointment_slots_practitioner_id_starts_at_idx" ON "appointment_slots"("practitioner_id", "starts_at");
CREATE INDEX "appointment_slots_clinic_id_starts_at_idx" ON "appointment_slots"("clinic_id", "starts_at");
