CREATE TYPE "VerificationStatus" AS ENUM ('verified', 'unverified');

CREATE TABLE "user_verifications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "test_type_id" BIGINT NOT NULL,
    "clinic_id" BIGINT,
    "verified_by_user_id" BIGINT,
    "status" "VerificationStatus" NOT NULL,
    "tested_at" DATE,
    "verified_at" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "user_verifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    CONSTRAINT "user_verifications_test_type_id_fkey" FOREIGN KEY ("test_type_id") REFERENCES "test_types"("id") ON DELETE RESTRICT,
    CONSTRAINT "user_verifications_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE SET NULL,
    CONSTRAINT "user_verifications_verified_by_user_id_fkey" FOREIGN KEY ("verified_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL
);

CREATE INDEX "user_verifications_user_id_created_at_idx" ON "user_verifications"("user_id", "created_at");
CREATE INDEX "user_verifications_user_id_status_idx" ON "user_verifications"("user_id", "status");
CREATE INDEX "user_verifications_clinic_id_idx" ON "user_verifications"("clinic_id");
