CREATE TYPE "AppointmentStatus" AS ENUM ('booked', 'cancelled', 'completed', 'no_show');

CREATE TABLE "appointments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "slot_id" BIGINT NOT NULL,
    "status" "AppointmentStatus" NOT NULL DEFAULT 'booked',
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "appointments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    CONSTRAINT "appointments_slot_id_fkey" FOREIGN KEY ("slot_id") REFERENCES "appointment_slots"("id") ON DELETE RESTRICT
);

CREATE INDEX "appointments_user_id_created_at_idx" ON "appointments"("user_id", "created_at");
CREATE INDEX "appointments_slot_id_idx" ON "appointments"("slot_id");
