CREATE TABLE "order_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL,
    "test_kit_id" BIGINT NOT NULL,
    "qty" INTEGER NOT NULL,
    "unit_price_cents" INTEGER NOT NULL,
    CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE,
    CONSTRAINT "order_items_test_kit_id_fkey" FOREIGN KEY ("test_kit_id") REFERENCES "test_kits"("id") ON DELETE RESTRICT
);

CREATE INDEX "order_items_order_id_idx" ON "order_items"("order_id");
