CREATE TYPE "PartnerStatus" AS ENUM ('pending', 'accepted', 'rejected', 'blocked');

CREATE TABLE "partners" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "shared_by_user_id" BIGINT NOT NULL,
    "received_by_user_id" BIGINT NOT NULL,
    "status" "PartnerStatus" NOT NULL DEFAULT 'pending',
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "accepted_at" TIMESTAMP,
    "user_low" BIGINT GENERATED ALWAYS AS (LEAST("shared_by_user_id", "received_by_user_id")) STORED,
    "user_high" BIGINT GENERATED ALWAYS AS (GREATEST("shared_by_user_id", "received_by_user_id")) STORED,
    CONSTRAINT "partners_shared_by_user_id_fkey" FOREIGN KEY ("shared_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    CONSTRAINT "partners_received_by_user_id_fkey" FOREIGN KEY ("received_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    CONSTRAINT "partners_shared_received_check" CHECK ("shared_by_user_id" <> "received_by_user_id")
);

CREATE UNIQUE INDEX "partners_user_low_user_high_key" ON "partners"("user_low", "user_high");
CREATE INDEX "partners_shared_by_user_id_idx" ON "partners"("shared_by_user_id");
CREATE INDEX "partners_received_by_user_id_idx" ON "partners"("received_by_user_id");
