CREATE TABLE "practitioner_clinics" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "practitioner_id" BIGINT NOT NULL,
    "clinic_id" BIGINT NOT NULL,
    CONSTRAINT "practitioner_clinics_practitioner_id_fkey" FOREIGN KEY ("practitioner_id") REFERENCES "practitioners"("id") ON DELETE CASCADE,
    CONSTRAINT "practitioner_clinics_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "practitioner_clinics_practitioner_id_clinic_id_key" ON "practitioner_clinics"("practitioner_id", "clinic_id");
CREATE INDEX "practitioner_clinics_clinic_id_idx" ON "practitioner_clinics"("clinic_id");
